version: "2"
authtoken: 35oSqeiiyi6BrKJ0uXr8wOioS2R_Cae4vGtcGbqmM27CELRw

tunnels:
  public_app:
    proto: http
    addr: haproxy-web:8080
    domain: https://bella-nonabstaining-bewilderedly.ngrok-free.dev
    inspect: true